### ISSUE TITLE
1.3.2: the "active" option doesn't changes icon color when the "entity" option indicated

### ISSUE THREAD

**Issue by ech0-py** [thomasloven/lovelace-template-entity-row#107]
The "entity" option is required when you wanna use actions, but it seems entity's icon color takes precedence over "active" icon
The state_color: true/false of entities card changes nothing

![issue_1](https://user-images.githubusercontent.com/415353/230999538-a7fe1f36-9648-46ce-9f4d-e0f2e62f8548.png)
![issue_2](https://user-images.githubusercontent.com/415353/230999542-54f3966c-3d38-4789-84da-4ef5383297ec.png)
```yaml
type: entities
entities:
  - type: custom:template-entity-row
    entity: automation.heating_night_tariff
    icon: mdi:home-automation
    name: Automation
    state: '{{ states("automation.heating_night_tariff") }}'
    active: '{{ is_state("automation.heating_night_tariff", "on") }}'
    tap_action: none
    hold_action:
      action: more-info
    double_tap_action:
      action: call-service
      service: automation.trigger
      data:
        entity_id: automation.heating_night_tariff
        skip_condition: true
```

Browser: Chrome 111.0.5563.148 (or hass companion app, android)
Hass: 2023.4.2
template-entity-row: 1.3.2 (HACS install)
