### ISSUE TITLE
Localization issue with 2023.4.4

### ISSUE THREAD

**Issue by BoneheadFraggle** [thomasloven/lovelace-template-entity-row#109]
I have a localization that has worked fine until I updated to 2023.4.4 just now:

```
            {% if states[config.entity].last_changed is defined %} Poolpumpen är
            _(component.switch.state._.{{ states.switch.ip44plug02.state }}) men
            enligt schemat borde den vara _(component.switch.state._.{{
            states('input_boolean.poolpump_schedule_active') }}) {% endif %}
```

Now it looks like this:
![image](https://user-images.githubusercontent.com/2287810/231845556-fe3f4391-1f17-4c3e-af45-25b599d75fe2.png)

I'll downgrade to 2023.4.3, just thought I'd notify.

**Comment by ildar170975** [comment]
Stopped working in 2023.4.4.
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: person.ildar
    state: _(component.device_tracker.state._.{{states(config.entity)}})
  - type: custom:template-entity-row
    entity: sun.sun
    state: |
      {{'_(component.device_tracker.state._.not_home)'}}
```
![image](https://user-images.githubusercontent.com/71872483/231873033-13121612-9d92-4e4a-b27d-313e4861d2a2.png)

**Comment by ildar170975** [comment]
Probably happened since localization key was changed:
```
{{'_(component.device_tracker.entity_component._.state.not_home)'}}
```
must be changed to
```
{{'_(component.device_tracker.state._.not_home)'}}
```

Example:
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: person.ildar
    state: >-
      _(component.device_tracker.entity_component._.state.{{states(config.entity)}})
  - type: custom:template-entity-row
    entity: sun.sun
    state: |
      {{'_(component.device_tracker.entity_component._.state.not_home)'}}
```
![изображение](https://user-images.githubusercontent.com/71872483/235910115-5ffe705a-c452-4e2d-8b13-ceef8cace511.png)
