### ISSUE TITLE
Templating card image fails

### ISSUE THREAD

**Issue by oywino** [thomasloven/lovelace-template-entity-row#111]
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: sensor.billigste_stasjon
    image: {{ state_attrib(sensor.billigste_stasjon, 'pictureurl') }}

title: Drivstoffpriser
```
If I type the pictureurl manually, it works just fine:

![image](https://user-images.githubusercontent.com/18447119/234028274-d5907d9f-6b87-4dcf-97de-3b77d28443ff.png)

I have tried all possible combinations of single and double quates without any luck. 
Is it possible to customize the card image using `template-entity-row` at all??
