### ISSUE TITLE
Template errors fload my log file

### ISSUE THREAD

**Issue by erkr** [thomasloven/lovelace-template-entity-row#114]
Since recent (guess core 2023.9.x), editing templates in the card floads my HA log file with hundreds of intermediate template errors (as the template code is invalid during editing). Log errors even continues to pop-up long (hours) after editing.
I don't exclude the option this is caused by the parent card (collapsible card)

**Comment by ildar170975** [comment]
Do not observe this.
2023.10.2
Win10x64+Chrome

![изображение](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/74a4aeaa-754a-4272-bb62-cb88e538f194)
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: sun.sun
    state: '{{states(config.entity)}}'
  - type: custom:template-entity-row
    entity: sun.sun
    state: '{{sttes(config.entity) sdadd daddad}}'
```
