### ISSUE TITLE
using it with Cover 

### ISSUE THREAD

**Issue by Winzy54** [thomasloven/lovelace-template-entity-row#117]
hello. 
i used the custom:template-entity-row and it looks very good. but when i used it for seconday on my cover, i lose the ability to change the cover position. 

thats the code i used:
entity: cover.stairs
type: custom:template-entity-row
secondary: >-
{% if is_state(‘binary_sensor.stairs’, ‘on’)%} Window is Open {% else %}
Window is Closed {% endif %}

when i dont use the custom:template-entity-row then on the stairs window i also have the option to move the cover like the “Middle” cover.

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/152816814/4a1ec61e-4215-435a-84a7-00527cdf3239)

**Comment by ildar170975** [comment]
1. You posted an unformatted code which cannot be analysed, you should have noticed it by yourself.
2. The template-entity-row card is not supposed to show controls. It is meant to show templated name, icon, state, secondary-info & some other options of a standard entity-row.

**Comment by Winzy54** [comment]
hi. 
first of all thanks for your answer. 
I am a real Newbie to HA and github, so sorry about my post. 

and i thought the main entity could stay as normal (with control) and i could use template entity row only for the secondary info. 
did i understand it wrong ?

**Comment by Winzy54** [comment]
Here is the whole code for it. 
hope i posted it correctly now

```
type: entities
entities:
  - entity: cover.stairs
    type: custom:template-entity-row
    secondary: >-
      {% if is_state('binary_sensor.stairs', 'on')%} Window is Open {% else %}
      Window is Closed {% endif %}
  - entity: cover.middle
  - entity: cover.kitchen_2
  - entity: binary_sensor.kitchen
show_header_toggle: true
title: Living Room
state_color: true
```
