### ISSUE TITLE
"tap_action" in json does not work

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-template-entity-row#119]
Strange, this functionality used to work.

Consider this:
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: input_boolean.test_boolean
    tap_action: |
      {
        "action": "toggle"
      }
  - type: custom:template-entity-row
    entity: input_boolean.test_boolean
    tap_action:
      action: toggle
```
Here `tap_action` works only in the 2nd row.

ver 1.4.0
2024.2.1
