### ISSUE TITLE
Colors of icons changing with recent versions

### ISSUE THREAD

**Issue by martkopecky** [thomasloven/lovelace-template-entity-row#123]
Not sure if this is a bug or a feature, but with one of the last plugin versions & update to HA 2024.02, the colors of the icon for template-entity-rows have started changing based on the underlying entity state. I've seen yellow/amber for toggle: on and also purple in some cases. 

For now, it can be cured by specifying `color: var(--paper-item-icon-color)` explicitly.

I can see no such behavior on the automatically generated dashboard, so I expect that this whole color changing is not something new in the core components just being inherited to the template entity row.

Sorry for the vague description. Here an example of amber icon:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/33658071/6152e18f-eeb9-4271-9df5-d78706c75272)

**Comment by ildar170975** [comment]
> the colors of the icon for template-entity-rows have started changing based on the underlying entity state. I've seen yellow/amber for toggle: on and also purple in some cases.

This is normal & expected in Entities card with "state_color: true" defined.

**Comment by martkopecky** [comment]
I have no such card defined in my dashboard, they either don't have the state_color attribute at all or they are set to false. Based on the docs, false is default. [](https://www.home-assistant.io/dashboards/entities/) 

So I think the root cause is somewhere else...

**Comment by thomasloven** [comment]
There was some buggy behaviour around this introduced in a recent version of Home Assistant. Work is currently ongoing to determine what is the right behavior, and then to fix it.

**Comment by Mariusthvdb** [comment]
not sure if this is the same, but template-entity-row does not follow `state_color: true` when doing 

```
type: entities
state_color: true
entities:

  - type: custom:template-entity-row
    entity: sensor.slaapkamer_hygro_temp_battery
```

<img width="502" alt="Scherm­afbeelding 2024-03-11 om 13 25 07" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/3bb95d13-7ad8-4444-9929-a9440efad511">

while its more-info does show the correct state_color:

<img width="571" alt="Scherm­afbeelding 2024-03-11 om 13 25 17" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/df274b3d-53a7-41c2-8837-8295ff269bb6">


we can set an explicit card_mod on it:
```
      - type: custom:template-entity-row
        entity: sensor.slaapkamer_hygro_temp_battery
        card_mod: !include /config/dashboard/card_mods/battery_color.yaml
```

which does:

<img width="520" alt="Scherm­afbeelding 2024-03-11 om 13 28 12" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/a375cb0e-698b-4545-95dc-5ac52d52012a">

currently testing with

Core
2024.4.0.dev20240311
Frontend
20240308.0.dev

**Comment by ildar170975** [comment]
> this is the same, but template-entity-row does not follow `state_color: true` when doing

This was broken in 2024.3.

**Comment by chemelli74** [comment]
Seems there is something more:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/57354320/3750eeef-cfdb-491b-bb7d-765b28bf2dfa)

**Comment by ildar170975** [comment]
@chemelli74 yes, same issue

**Comment by chemelli74** [comment]
> @chemelli74 yes, same issue

Sorry, I may miss something but core itself shows green color (which is correct), while template row not.
Isn't it an issue on this custom card code ?

**Comment by ganjakyp-hub** [comment]
Is there any solution to this problem?

**Comment by Mariusthvdb** [comment]
getting back to this, because after testing 2024.7.beta, I now also see that the active options is not set when using below config, nor is the icon properly inherited from the entity, as the documentation explains/instructs:

```
      - type: custom:template-entity-row
        entity: device_tracker.private_ble_device_marijn
        active: >
          {{is_state(config.entity,'home')}}
```

should light up properly (it did before) and change to the connected icon:

this it the template entity row:

<img width="520" alt="Scherm­afbeelding 2024-06-27 om 16 22 22" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/8a38ce7e-08da-4a8f-a494-3ae2b829b480">

and yes, ive also set` state_color: true` in the containing entities card.

this is the correct more info:

<img width="582" alt="Scherm­afbeelding 2024-06-27 om 16 22 29" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/1968e917-0e81-4f60-aaa8-cd0562959c55">

coloring according to the theme colors, and setting the i[con according to the device](https://github.com/home-assistant/core/blob/dev/homeassistant/components/private_ble_device/icons.json)

could it be relatively new Icon translations are not yet supported and we need to explicitly template those now?

**Comment by ildar170975** [comment]
Imho `active` is not working for some long time.
For instance, in 2024.6.4 it does not work:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/da47182d-da44-455e-93b7-e5b7de24b30e)

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/41c4b85a-d20d-4816-a4a5-4480bb3c39a4)

**Comment by Mariusthvdb** [comment]
thanks for confirming, I wasnt sure.

However, I am sure it did work when I created this card, and that was short after the private Ble were introduced, and a bit later when the state_translated was introduced.

dont believe the template-entity-row has the `state_color: ` option though? (the bottom example of your post.)

anyways, I really hope this magic card will see an update sometime.

maybe I should open a separate issue for the icon (didnt check yet if there already is one), to keep it as clear and clean as possible to track

**Comment by ildar170975** [comment]
> dont believe the template-entity-row has the state_color: option though? (the bottom example of your post.)

Added this example just in case.

**Comment by ildar170975** [comment]
According to my log, "active" was not working by "06.04.23".

**Comment by maximuswallis** [comment]
Hi,
A workaround to this problem is adding this to the entity:

```
color: |
  {% if is_state('switch.your_switch_here', 'on') %}
    var(--state-active-color)
  {% elif is_state('switch.your_switch_here', 'off') %}
    var(--state-inactive-color)
  {% else %}
    var(--disabled-color)
  {% endif %}
```

I hope this helps someone!

**Comment by arigit** [comment]
still an issue as of 2024.10.2; thanks @maximuswallis  for the workaround!

**Comment by melyux** [comment]
@maximuswallis You can use "config.entity" variable instead of having to specify the entity ID again for this.

But also, this is still broken.

**Comment by chemelli74** [comment]
Hi, any update on this issue ?

**Comment by jasondostal** [comment]
Curious on the same, I think I am experiencing the same issue in my HA instance.

**Comment by Mariusthvdb** [comment]
still broken, bu card_mod can be a temporary band_aid

```

type: custom:auto-entities
card:
  type: entities
  title: Recente Automaten
  card_mod:
    class: class-header-margin
  show_header_toggle: false
  state_color: true # <-- not functional on template-entity-row
show_empty: false
filter:
  include:
    - domain: automation
      state: 'on'
      last_triggered: '<= 20'
      options:
        type: custom:template-entity-row
        card_mod:
          style: |
            :host {
              --card-mod-icon-color:
                {{'var(--active-color)' if is_state(config.entity,'on')}};
              }
        # active is also lost since forever....
        active: >
          {{is_state(config.entity,'on')}}
```
