### ISSUE TITLE
secondary info template

### ISSUE THREAD

**Issue by hiagocosta** [thomasloven/lovelace-template-entity-row#124]
hi,
i'm trying to implement the templantes on a row for my Fire Tablet, that will inform it's currently situation, if is charging or not, 
but I think that my logics is good enough...

I miss a bit

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/22087481/a507b87c-2a9e-4fe1-b22a-d05cb8edfc34)

**Comment by hiagocosta** [comment]
this is the full coding of this card:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/22087481/b69ce7e5-6874-477a-88f4-7d7c059be811)

**Comment by ildar170975** [comment]
1. In future: post a real formatted code, not it's image.
2. There is no `secondary_info` option, it is `secondary`.

**Comment by hiagocosta** [comment]
sorry, 
this is de the code of the card at all, still not picking the template 

```
type: entities
entities:
  - entity: sensor.ble_battery_sensor_sala
    name: Termômetro Sala
  - entity: sensor.ble_battery_sensor_escritorio
    name: Termômetro Escritório
  - entity: sensor.ble_battery_sensor_quarto
    name: Termômetro Quarto
  - entity: sensor.ble_battery_sensor_externo
    name: Termômetro Externo
  - entity: sensor.ble_battery_sensor_banheiro
    name: Termômetro Banheiro
  - entity: sensor.ble_battery_sensor_cozinha
    name: Termômetro Cozinha
  - type: custom:template-entity-row
    entity: sensor.fire_tablet_battery
    secondary: >-
      {{% if is_state('binary_sensor.fire_tablet_plugged_in' , 'on') %}}
      Carregando {{% endif %}}
  - entity: sensor.mi_9_battery_level
    name: Xiaomi Mi9
    secondary_info: last-changed
  - entity: sensor.watch_6_battery_level
    name: Galaxy Watch 6
    secondary_info: last-updated
title: Nível de Bateria
theme: Mushroom Shadow
state_color: true
```

**Comment by ildar170975** [comment]
Because templates are wrong.
```
{{% ... %}}
```
must be
```
{% ... %}
```

**Comment by hiagocosta** [comment]
now it works, thansk for help!!
by the way, this is shows as integer, how can I add in percentage?

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/22087481/09f571f4-0122-430a-95b4-252d733b2da0)

**Comment by Misiu** [comment]
@hiagocosta I think it is the same bug as described here: https://github.com/thomasloven/lovelace-template-entity-row/issues/62

Use state template, something like this:
```
state:  '{{ state("sensor.fire_tablet_battery") }} %'
```

**Comment by ildar170975** [comment]
> I think it is the same bug as described here

That issue https://github.com/thomasloven/lovelace-template-entity-row/issues/62 is not a bug - OP created it because he expected smth which is not supported. And did not close the issue after receiving explanations.
Also, that issue https://github.com/thomasloven/lovelace-template-entity-row/issues/62 is not related to the current issue - here it is about wrong use of jinja.
I wonder why both issues are still open.

**Comment by Misiu** [comment]
@ildar170975 I was only replying about the last question of OP because I had a similar issue with missing units:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/1741838/e902c655-a0e6-448a-8c99-9ab68dae8db8)

```
type: entities
entities:
  - entity: sensor.x_cloud_days_until_expiration
  - entity: sensor.x_cloud_days_until_expiration
    type: custom:template-entity-row
```
the `default` row shows the unit when the `[template-entity-row](custom:template-entity-row)` is missing it.
I suggested using a template for the state as I'm doing: https://community.home-assistant.io/t/auto-entities-customize-displayed-name-and-use-attribute-as-secondary-info/700415/1
