### ISSUE TITLE
Im sure my formatting is wrong - [object Object]

### ISSUE THREAD

**Issue by DeFlanko** [thomasloven/lovelace-template-entity-row#127]
```yaml
type: entities
entities:
  - entity: sensor.run_counter_garden
  - type: custom:template-entity-row
    state: {{states(sensor.run_counter_grass)| float(0) | multiply(5) | round(0) }}
    name: Garden ran for
  - entity: sensor.run_counter_flowers
    name: Flowers
  - entity: sensor.run_counter_grass
    name: Grass
state_color: true
title: 'Water Run times '
```

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/5233969/fae2cbe2-6f76-49e0-9157-192711fb426a)

any guidance would be greatly appreciated as to what im doing wrong here... 

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/5233969/ea1290e6-d1fc-4eca-ba3f-f6a4d4f5d96d)

**Comment by ildar170975** [comment]
```
state: {{states(sensor.run_counter_grass)| float(0) | multiply(5) | round(0) }}
```
Since you tested the template in Dev tools - you could have noticed a difference in the card's code, it has errors - must be `states('sensor.run_counter_grass')`.
Besides, the whole template must be a string:
```
state: >-
  {{ states('sensor.run_counter_grass')| float(0) | multiply(5) | round(0) }}
```
or
```
state: "{{ states('sensor.run_counter_grass')| float(0) | multiply(5) | round(0) }}"
```
or
```
state: '{{ states(''sensor.run_counter_grass'')| float(0) | multiply(5) | round(0) }}'
```

**Comment by DeFlanko** [comment]
THANK YOU! (kinda feel dumb now.. lol)

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    name: >-
      Garden ran for {{ states('sensor.run_counter_garden')| float(0) |
      multiply(5) | round(0) }} min
  - type: custom:template-entity-row
    name: >-
      Flowers ran for {{ states('sensor.run_counter_flowers')| float(0) |
      multiply(5) | round(0) }} min
  - type: custom:template-entity-row
    name: >-
      Grass ran for {{ states('sensor.run_counter_grass')| float(0) |
      multiply(5) | round(0) }} min
  - type: custom:template-entity-row
    name: Total Run time for all stations was {{ (states('sensor.run_counter_grass') | float(0) | multiply(5) | round(0)) + (states('sensor.run_counter_garden') | float(0) | multiply(5) | round(0)) + (states('sensor.run_counter_flowers') | float(0) | multiply(5) | round(0)) }} min 
state_color: true
title: 'Water Run times '

```

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/5233969/6ee328ed-9575-4484-bac9-9a89cab00fab)
