### ISSUE TITLE
icon not set for core entity device_tracker

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#128]
using below config for a device_tracker has a few issues:
```
    entities:
      - type: custom:template-entity-row
        entity: device_tracker.private_ble_device_marijn
        active: >
          {{is_state(config.entity,'home')}}
        state: >-
          {{state_translated(config.entity)}}
        secondary: >
          Verbonden: {{states('sensor.private_ble_device_marijn_connection')}}
```
one of them is the icon_color, or active, which is not set anymore, but there is[ an open issue](https://github.com/thomasloven/lovelace-template-entity-row/issues/123#issuecomment-2194859160) for that.

This issue is about the _icon itself not being set_. 

while it should be `bluetooth-connect` when Home

<img width="582" alt="Scherm­afbeelding 2024-06-27 om 16 22 29" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/1a60c0da-bf90-414c-9222-bae1df9abb0f">

it uses `bluetooth-off`:

<img width="520" alt="Scherm­afbeelding 2024-06-27 om 16 22 22" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/4b448142-2b7c-49ca-9a24-d04fca63fa32">

while as you can see the tracker is Home (Thuis) and connected to its adapter.

I can force it to set the correct icon by adding the icon template
```
        icon: >
          {{state_attr('sensor.private_ble_device_marijn_connection','icon')}}
```

but, that in itself is a template entity, which is a bit odd to use in this card, when the entity itself has the correct icon 'translation' set in https://github.com/home-assistant/core/blob/dev/homeassistant/components/private_ble_device/icons.json

```
{
  "entity": {
    "device_tracker": {
      "device_tracker": {
        "default": "mdi:bluetooth-off",
        "state": {
          "home": "mdi:bluetooth-connect"
        }
      }
    },
    "sensor": {
      "estimated_distance": {
        "default": "mdi:signal-distance-variant"
      },
      "estimated_broadcast_interval": {
        "default": "mdi:timer-sync-outline"
      }
    }
  }
}
```

could it be the new icon translations are not yet supported in template-entity-row, because, as [the documentation states](https://github.com/thomasloven/lovelace-template-entity-row?tab=readme-ov-file#options):

> entity if this evaluates to an entity id, icon, name, state and image will be taken from that entity unless manually overridden. 

indicate they should be fine in this particular config using an entity.
Please have a look. thx.

**Comment by ildar170975** [comment]
For `input_boolean` & `binary_sensor`  domains - see no issues:

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/ea40f6a7-fd8d-4483-8736-e1362cffecf1)

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/d7c618b8-be5a-4b5b-96eb-169404ff895d)

```
    type: entities
    entities:
      - input_boolean.testing_boolean
      - type: custom:template-entity-row
        entity: input_boolean.testing_boolean
      - type: section
      - binary_sensor.testing_device_class_connectivity
      - type: custom:template-entity-row
        entity: binary_sensor.testing_device_class_connectivity
```
Same for `automation`.
