### ISSUE TITLE
templates unstable on HA 105.2

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#13]
ever since updating to 105.x the templates in my config below are constantly going back and forth between the full template code being displayed in the frontend, and the output these templates should create. They worked perfectly up to HA 104.3.

```
  - type: custom:auto-entities
    card:
      type: entities
      title: Github repos
      show_header_toggle: false
    entities:
      - entity: automation.github_repo_update
        secondary_info: last-triggered
    filter:
      include:
        - entity_id: sensor.github*
          options:
            type: custom:template-entity-row
            state: >
              {% if state_attr(config.entity,'latest_release_url') %}
              {{ state_attr(config.entity,'latest_release_url').split('tag/')[1]}}
              {% else %} Not set
              {% endif %}
            secondary: >
              {{ state_attr(config.entity,'latest_commit_message')}}
```

Ive tested the same config with the dummy-row card, and that is fully stable, thus taking out the auto-entities card as possible cause for this issue
```
  - type: custom:auto-entities
    card:
      type: entities
      title: Github repos
      show_header_toggle: false
    entities:
      - entity: automation.github_repo_update
        secondary_info: last-triggered
    filter:
      include:
        - entity_id: sensor.github*
          options:
            type: custom:dummy-entity-row
#            state: >
#              {% if state_attr(config.entity,'latest_release_url') %}
#              {{ state_attr(config.entity,'latest_release_url').split('tag/')[1]}}
#              {% else %} Not set
#              {% endif %}
#            secondary: >
#              {{ state_attr(config.entity,'latest_commit_message')}}
  #            secondary: "{{ as_timestamp(states[config.entity].last_changed)| timestamp_custom('%X - %D') }}"
          sort:
            method: name
```

please have a look what could be causing the templates not to show up stable?

<img width="554" alt="Schermafbeelding 2020-02-07 om 00 38 00" src="https://user-images.githubusercontent.com/33354141/74025905-48eacb80-49a5-11ea-94a3-45d29784b8f2.png">

see also report on https://community.home-assistant.io/t/template-entity-row-put-templates-in-an-entities-row/160167/25?u=mariusthvdb
