### ISSUE TITLE
How do I put this template into the state of a Lovelace card?

### ISSUE THREAD

**Issue by ars4l4n** [thomasloven/lovelace-template-entity-row#130]
This is what I'm currently using as a template sensor:
```
% set hours = states('sensor.wie_lang_zuletzt_geschlafen') | float %}
{% set minutes = ((hours % 1) * 60) | int %}
{% set hours = (hours - (hours % 1)) | int %}
{{ '%02i:%02i'%(hours, minutes)}} h
```
This is how my Lovelace card looks like:
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: sensor.wie_lang_zuletzt_geschlafen
```
But how do I put the two together?

**Comment by ildar170975** [comment]
Try:
```

type: entities
entities:
  - type: custom:template-entity-row
    entity: sensor.wie_lang_zuletzt_geschlafen
    state: >-
      … your template …
```

This is a question, not a bug or feature request. 
Suggest to post questions in Community.
