### ISSUE TITLE
Feature Request: pick any entity for tap_action, hold_action

### ISSUE THREAD

**Issue by arigit** [thomasloven/lovelace-template-entity-row#131]
My use case: I use template entity row to aggregate data from multiple sensors, e.g. temp and humidity, as in the example below.
when the entity is tapped, I want to display more-info for one of the sensors, and when the entity is "hold" (or double tapped etc) I want to display more-info for another sensor.

This functionality is supported in multiple-entity-row and custom-button-card, they support the syntax I include in the example below. Could template-entity-row support the same?

```
      - type: entities
        title: Cold Room
        entities:
          - type: custom:template-entity-row
            name: Temp | Humidity
            icon: mdi:thermometer-water
            state: "{{ states('sensor.zw100_cold_room_air_temperature') + ' °C | ' + states('sensor.zw100_cold_room_humidity') + ' %' }}"
            entity: sensor.zw100_cold_room_humidity
            tap_action:
              entity: sensor.zw100_cold_room_air_temperature
              action: more-info
            hold_action:
              entity: sensor.zw100_cold_room_humidity
              action: more-info       
```
