### ISSUE TITLE
Icon State Color variable not functioning

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [thomasloven/lovelace-template-entity-row#136]
With `state_color: true` set, the icon color remains the default color.

```
type: custom:template-entity-row
entity: sensor.front_door_battery_level
state_color: true
state: >
  {{ states(config.entity) }} {{ state_attr(config.entity,
  'unit_of_measurement') }}
name: >
  {{ state_attr('config.entity','friendly_name') |
  regex_replace("(Battery|Level)", "") }}
```

![Image](https://github.com/user-attachments/assets/73eb4c01-777f-46ef-8780-2b5d1a7cddbc)

**Comment by jasondostal** [comment]
I think we might be experiencing the same issue?  Recently, every icon on my HA dashboards that is rendered via template-entity-row has stopped showing its active color when it is active.

Here's one of my Entity cards as an example.  On this card, I use template-entity-row to display additional information associated with the motion sensor tied to these switches/lights.

All of my entities I'm displaying using this are no longer working.

I have a set of lamps I'm displaying using fold-entity-row and they seem to still be indicating state correctly.


<img width="419" height="401" alt="Image" src="https://github.com/user-attachments/assets/0e9d8370-b762-462f-8b0f-9939225c1581" />

**Comment by sciurius** [comment]
This may or may not be related: I've noticed that some of the `custom:template-entity-row` cards do not update everything adequately. 

For example,

````
  - type: custom:template-entity-row
    icon: mdi:water-boiler
    name: Ext Boiler
    entity: switch.extboiler
    toggle: true
    color: |
      {% if is_state('input_boolean.extboiler_hot','on') %} green
      {% else %}
        {% if (states('sensor.extboiler_energy_power')|float) > 1 %} yellow
        {% else %} none
        {% endif %}
      {% endif %}
    secondary: |
      Verbruik {{ states('sensor.extboiler_energy_today') }} kWh
````

The state of the switch is updated if necessary but it seems that the icon color and secondary information is not (always) updated. As if `custom:template-entity-row` doesn't listen to the correct events anymore, or that HA has changed the events...

**Comment by Mariusthvdb** [comment]
> With `state_color: true` set, the icon color remains the default color.

state_color is not an [option for template-entity-row](https://github.com/thomasloven/lovelace-template-entity-row?tab=readme-ov-file#options), but for type: entities card.

having said that, even the native option to template-entity-row, `active`, is broken, and does not set the color to the icon.

see https://github.com/thomasloven/lovelace-template-entity-row/issues/123#issuecomment-1988324238

This has been going on for some time....., and the only option we have until this will be fixed, is setting a card_mod to the row:

real life example that works
```
type: custom:auto-entities
card:
  type: entities
  title: Recente Automaten
  card_mod:
    class: class-header-margin
  show_header_toggle: false
  state_color: true # <-- not functional on template-entity-row
show_empty: false
filter:
  include:
    - domain: automation
      state: 'on'
      last_triggered: '<= 20'
      options:
        type: custom:template-entity-row
        card_mod:
          style: |
            :host {
              --card-mod-icon-color:
                {{'var(--active-color)' if is_state(config.entity,'on')}};
              }
        # active is also lost since forever....
        active: >
          {{is_state(config.entity,'on')}}
        toggle: true
        secondary: >
          {% if state_attr(config.entity,'last_triggered') %}
          {{relative_time(state_attr(config.entity,'last_triggered'))}} ago
          {% else %} Never triggered
          {% endif %}
        hold_action: |
          {
            "action": "navigate",
            "navigation_path": "/config/automation/trace/{{states[config.entity].object_id}}"
          }
  exclude:
    - entity_id: '*awtrix*'
    - attributes:
        last_triggered: null
sort:
  method: last_triggered
  reverse: true
```
