### ISSUE TITLE
Error saving card in lovelace

### ISSUE THREAD

**Issue by stast1** [thomasloven/lovelace-template-entity-row#14]
When editing a card in lovelace, the value of the template is saved instead of the template itself.

![image](https://user-images.githubusercontent.com/48147949/74214775-7d150380-4ca7-11ea-862d-dd7cbccf7266.png)

Click Save and Edit

![image](https://user-images.githubusercontent.com/48147949/74214850-b6e60a00-4ca7-11ea-8cfe-b2224370c590.png)

![image](https://user-images.githubusercontent.com/48147949/74214937-09bfc180-4ca8-11ea-86ba-28c2c9b0d377.png)

**Comment by jacekpaszkowski** [comment]
same issue here. it seems that during save template is evaluated and then saved in lovelace yaml

**Comment by basnijholt** [comment]
I have the exact same:
```
type: entities
entities:
  - entity: binary_sensor.dishwasher
    name: Dishwasher
    secondary: >
      {% set on_for = as_timestamp(now()) - as_timestamp(states('input_datetime.dishwasher_started')) %}
      {% set off_for = as_timestamp(now()) - as_timestamp(states('input_datetime.dishwasher_done')) %}
      {% if states('binary_sensor.dishwasher') == 'on' %}
        Has been on for {{ (on_for / 60)|round(0) }} minutes.
      {% else %}
        Has been off for {{ (off_for / 3600)|round(1) }} hours.
      {% endif %}
    state: >
      {% if is_state('binary_sensor.dishwasher', 'on') %}
        {{ states('sensor.dishwasher_watts') }} Watt
      {% else %}
        Off
      {% endif %}
    type: custom:template-entity-row
```
turns into 
```
type: entities
entities:
  - entity: binary_sensor.dishwasher
    name: Dishwasher
    secondary: Has been off for 22.4 hours.
    state: 'Off'
    type: 'custom:template-entity-row'
```


I have HA 0.105.2 and `template-entity-row` at https://github.com/thomasloven/lovelace-template-entity-row/commit/81bf4990aaa4536a096dfd53023e0d3469942899.
