### ISSUE TITLE
name and secondary too close to image

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#21]
using:

```
#card:
#  type: custom:secondaryinfo-entity-row
#  entity: '[[entity]]'
#  secondary_info: '[[ {entity}.attributes.type ]]: [[ {entity}.attributes.original_date ]]'

card:
  type: custom:template-entity-row
  entity: '[[entity]]'
  secondary: >
    {{states.[[entity]].attributes.type}}: {{states.[[entity]].attributes.original_date}}
#  name: '{{states.[[entity]].attributes.friendly_name}}'
#  state: '{{states.[[entity]].state}}'
#  image: '{{states.[[entity]].attributes.entity_picture}}'
```
in a decluttering card causes the name and secondary_info to be placed too closely to the entity_picture of the row. 
![wrong](https://user-images.githubusercontent.com/33354141/77050544-3616de00-69ca-11ea-898a-804b47367164.png)

Compare that to the commented secondary info-entity-row code, which places it correctly:

![correct](https://user-images.githubusercontent.com/33354141/77050567-3fa04600-69ca-11ea-8bb1-d1047436ed41.png)

and uses the 'normal' space between image and name in a entity row, like:

<img width="369" alt="Schermafbeelding 2020-03-19 om 09 56 08" src="https://user-images.githubusercontent.com/33354141/77050635-58106080-69ca-11ea-93c0-e52a7062b1c9.png">

furthermore, it doesn't show the unit_of_measurement, isn't that taken from the entity? if not, please add that too?

<img width="775" alt="Schermafbeelding 2020-03-19 om 10 18 48" src="https://user-images.githubusercontent.com/33354141/77051204-3b285d00-69cb-11ea-9f37-7295b2db6cf2.png">

please have a look?

HA 106.6  T-E-R 1.1.0
thanks
ps also discussed in the [community](https://community.home-assistant.io/t/template-entity-row-momentarily-displays-its-templates/179447/6?u=mariusthvdb)

**Comment by thomasloven** [comment]
Is this fixed? I think it is..?

**Comment by Mariusthvdb** [comment]
yes! well, almost. spacing is perfect, thank you sir!

no unit yet though, is that something you are still looking in to please?

<img width="397" alt="Schermafbeelding 2020-04-15 om 09 17 22" src="https://user-images.githubusercontent.com/33354141/79309093-07712200-7efa-11ea-8503-6ede61b7d636.png">

**Comment by thomasloven** [comment]
The unit's right there in the attributes. Use templating to put it wherever you want it.

**Comment by Mariusthvdb** [comment]
Well, im puzzled, I thought to have tried all...
please give me a hint how to get the attribute
```
{{states.[[entity]].attributes.unit_of_measurement}}
```

on the 'official' spot for unit? Its not for the 'secondary' line, but since this is using 'entity', there is no placeholder for anything besides that?

**Comment by thomasloven** [comment]
By putting in in the `state:` just like the state.

`state: "{{states(config.entity)}} {{state_attr(config.entity, 'unit_of_measurement')}}"`

This row is *all* about configurability. Having it do everything automatically would ruin the point.

**Comment by Mariusthvdb** [comment]
ok thanks, will do. cool.

not using the 'state' now, this
```
card:
  type: custom:template-entity-row
  entity: '[[entity]]'
  secondary: >
    {{states.[[entity]].attributes.type}}: {{states.[[entity]].attributes.original_date}}
```

works just fine ;-) exactly because it takes most automatically from the entity (3d bullet  in https://github.com/thomasloven/lovelace-template-entity-row#options)

could I FR adding unit_of_measurement there? It would allow it to be as close to regular entity if wanted, and still allow for all templating options for optimal configurability if so desired.
