### ISSUE TITLE
input_number does not work as expected

### ISSUE THREAD

**Issue by akasma74** [thomasloven/lovelace-template-entity-row#22]
HA: 0.106.6
This component: 1.1.0
Browser: Safari, Chrome
OS X 10.11.6

When I use this entity row for `input_number`, I get a read-only representation of it regardless of its `mode`.
Here is my config:
```yaml
type: entities
entities:
  - entity: automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_gradient
    name: by humidity gradient

  - type: custom:template-entity-row
    entity: input_number.ventilation_1st_floor_bathroom_shower_humidity_threshold
```
![Screen Shot 2020-03-22 at 21 22 32 (2)](https://user-images.githubusercontent.com/13675855/77261030-5f15c800-6c83-11ea-9fe9-4557e30f6fa5.png)
