### ISSUE TITLE
condition option does not work until reload

### ISSUE THREAD

**Issue by akasma74** [thomasloven/lovelace-template-entity-row#23]
HA: 0.106.6
This component: 1.1.0
Browser: Safari, Chrome
OS X 10.11.6

This simple config does not hide `input_number` regardless of the automation's state.
It only changes when I reload the page in my browser.
A commented string makes it work but it's not ideal.
```yaml
type: entities
entities:
  - entity: automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_gradient
    name: by humidity gradient

  - type: custom:template-entity-row
    entity: input_number.ventilation_1st_floor_bathroom_shower_humidity_threshold
    #entity_ids: automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_gradient
    condition: "{{ is_state('automation.ventilation_1st_floor_bathroom_extractor_fan_turn_on_by_humdity_gradient', 'on') }}"

```
