### ISSUE TITLE
templates are not re-evaluated despite having sensor.time in them

### ISSUE THREAD

**Issue by akasma74** [thomasloven/lovelace-template-entity-row#24]
I have the following config
```yaml
type: entities
title: Motion detectors
show_header_toggle: false
entities:
  - type: custom:template-entity-row
    entity: binary_sensor.pir_1st_floor_landing
    #entity_ids:
    #  - binary_sensor.pir_1st_floor_landing
    #  - sensor.time
    secondary: >
      {% set dt_obj = states.input_datetime.pir_1st_floor_landing %}
      {% set dummy = strptime(states('sensor.time'), '%H:%M') %}
      {% set aware_dt = dummy.fromtimestamp(dt_obj.attributes.timestamp, now().tzinfo) %}
      {{ relative_time(aware_dt) }} ago
```
and it does not update `secondary` unless I hit Reload or uncomment `entity_ids`.
HA 0.107.5, template-entity-row 1.1.0
