### ISSUE TITLE
Conditional Tap Action

### ISSUE THREAD

**Issue by dudu631** [thomasloven/lovelace-template-entity-row#26]
Is it possible to template the tap action, in order to only enable it on a certain state?

Example:
```
 tap_action: |-
      {% if is_state('media_player.tv_samsung', 'on')%}  
        action: call-service
        confirmation: 
            text: Turn off TV? 
        service: media_player.turn_off
        service_data: 
            entity_id: media_player.tv_samsung 
      {% endif %}
```

Or something like that?

**Comment by jschonenberg** [comment]
``` 
...
 include:
    - domain: timer
      entity_id: /chore/
      options:
        tap_action:
          action: call-service
          service: timer.start
          service_data:
            entity_id: "{{ config.entity }}"
...
```
