### ISSUE TITLE
Tap_action do not work with condition option

### ISSUE THREAD

**Issue by JanuszMarek** [thomasloven/lovelace-template-entity-row#28]
Hi,

I have following card config:
```
          - type: custom:template-entity-row
            entity: binary_sensor.sensor
            tap_action:
              action: more-info
            condition: "{{is_state('binary_sensor.sensor', 'on')}}"
```
And when 'condition' option is set tap_action do not work, after click nothing happens.
After comment out condition option tap_action is working correctly.

Home Assistant 0.111.4
