### ISSUE TITLE
Unknown error when using this with auto-entities

### ISSUE THREAD

**Issue by benjamfk** [thomasloven/lovelace-template-entity-row#32]
I have a really strange issue. I have a new HA install on a Raspberry Pi 4.
I've added the latest version of these through HACS:
* anniversaries (https://github.com/pinkywafer/Anniversaries)
* auto-entities (https://github.com/thomasloven/lovelace-auto-entities)
* lovelace-template-entity-row (https://github.com/thomasloven/lovelace-template-entity-row)

Configuration (anniversaries):
```
anniversaries:
  sensors:
  - name: Person A
    date: '1980-12-01'
    icon_today: mdi:party-popper
```

I then try to filter all of the entities and create the card.
My goal is to make a list of birthdays that show a sorted list with the age and birthday.
```
type: custom:auto-entities
card:
  type: entities
  title: Birthdays
  show_header_toggle: false
filter:
  include:
    - entity_id: sensor.anniversary*
      state: < 120
      sort:
        method: state
        numeric: true
```

That gives you something like this:
![image](https://user-images.githubusercontent.com/64400812/91075666-b955f300-e63e-11ea-911c-7f582761277f.png)

Then I wanted to use "lovelace-template-entity-row" to override "29 days" to "Today/Tommorrow/29 days" depending on the number of days left and also add a secondary_info saying for example: "35 Years old (01.12.1980)".

However whenever I modify the code to something like this:
```
type: custom:auto-entities
card:
  type: entities
  title: Birthdays
  show_header_toggle: false
filter:
  include:
    - entity_id: sensor.anniversary*
      state: < 120
      options:
        type: custom:template-entity-row
        secondary: >-
          {% if is_state(entity, '0') %}
            {{ state_attr(entity, 'current_years') }} Years
          {% else %}
            {{ state_attr(entity, 'years_at_next_anniversary') }} Years
          {% endif %}
            ({{ as_timestamp(state_attr(entity, 'date')) | timestamp_custom('%d.%m.%Y') }})
      sort:
        method: state
        numeric: true
```

and hit "Refresh" in HA I get "Unknown error / Reload UI". Hitting F5 brings the cached and working page back...
Any ideas on why I keep getting this error?
