### ISSUE TITLE
core-2021.6.0b0 - Entity required?

### ISSUE THREAD

**Issue by Scags104** [thomasloven/lovelace-template-entity-row#51]
seems all my templates are reporting "Entity not available: [empty]" as of the new version. 

Basic troubleshooting done:
- Add entity doesnt work
- clear cache doesnt work
- seems to react even more poorly with the secondary flag

**Comment by Mariusthvdb** [comment]
do you see a more-info popup at all, they wont open anymore in my configs

**Comment by thomasloven** [comment]
Please try version 1.2.0

**Comment by Scags104** [comment]
this actually began working (for me) as of 1.1.2 once Core 2021.6.0b4 was released.

Assumption: something they were doing with theming in this release? 

Either way we can mark this as closed. Thank you for this!

**Comment by lindsaymarkward** [comment]
I know this is a closed issue, but I thought I'd post here since it's the closest I can find to my issue. I'm happy to open a new issue if that's better.
I get "Entity not available: [empty]" where it used to work. The name and value still appear (the template works fine), but not as expected. There's no icon. I've tried this for a couple of entities, but get the same result. I'm using HA 2023.4.1 and template-entity-row 1.3.2.
Here's my UI YAML: 

```
    - type: entities
      show_header_toggle: false
      entities:
        - script.practice
        - type: custom:template-entity-row
          name: "Practice duration"
          icon: mdi:timer-sand
          state: "{{ states.input_number.practice_duration.state|int }}"
        - input_number.practice_duration
```

Thanks!
