### ISSUE TITLE
A few minor issues to be in parity with default lovelace

### ISSUE THREAD

**Issue by dooz127** [thomasloven/lovelace-template-entity-row#6]
1. Title capitalize text-based state:

![image](https://user-images.githubusercontent.com/19983618/72111112-b6480580-32ee-11ea-9d59-b3fc2f91e3e1.png)

2.  Use 'pretty' text state for persons

![image](https://user-images.githubusercontent.com/19983618/72111591-18553a80-32f0-11ea-8869-8bcb22649193.png)

3. 'Active' option does not appear to work on entities that are not switches or binary sensors. It was working on the previous iteration of template-entity-row.

![image](https://user-images.githubusercontent.com/19983618/72112191-bac1ed80-32f1-11ea-84ef-686747ae42f5.png)

```yaml
entities:
  - entity: person.duy_nguyen
  - entity: person.duy_nguyen
    active: true
    icon: '{{ state_attr(''person.duy_nguyen'',''icon'') }}'
    type: 'custom:template-entity-row'
  - entity: switch.front_door_light
    active: true
    type: 'custom:template-entity-row'
show_header_toggle: false
title: Template-entity-row Test
type: entities
```
