### ISSUE TITLE
FR: Add more-info option

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#66]
in a config without an entity, we now see a popup indicating `no entity provided for more-info dialog`. 

Adding an additional more info configuration option would be very nice, so we can set that, and even template that.

**Comment by emufan** [comment]
Would like to have this as well. define/template entity for the more-info dialog.

**Comment by florie1706** [comment]
+1

**Comment by dcapslock** [comment]
more-info action now accepts entity, so you can set directly or template the action per documentation.

**Comment by Mariusthvdb** [comment]
missed this before, sorry.

suppose it is fixed:
```
  - type: custom:template-entity-row
    state: ""
    name: Tap action
    tap_action:
      action: more-info
      entity: sun.sun
```
thanks!
