### ISSUE TITLE
Double tap action not working

### ISSUE THREAD

**Issue by joshuaspence** [thomasloven/lovelace-template-entity-row#67]
I am using the latest version of Home Assistant (2021.10.6) and `template-entity-row` (1.3.0). `double_tap_action` doesn't seem to work. I can reproduce the issue with the following configuration:

```yaml
type: 'entities'
entities:
  - entity: 'person.josh'
    tap_action:
      action: 'none'
    double_tap_action:
      action: 'more-info'

  - type: 'custom:template-entity-row'
    entity: 'person.josh'
    tap_action:
      action: 'none'
    double_tap_action:
      action: 'more-info'
```

Double-tapping on the first entity loads the `more-info` dialog but double-tapping on the second entity does nothing.
