### ISSUE TITLE
input_datetime don't accept data

### ISSUE THREAD

**Issue by DaniJulia** [thomasloven/lovelace-template-entity-row#69]
I created the following card:

```
type: entities
entities:
  - type: custom:template-entity-row
    name: Cat Sand
    entity: input_datetime.cat_sand
    tap_action:
      action: call-service
      confirmation: true
      service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.cat_sand
      data:
        date: '2020-08-24'

```

Keep saying me: "Failed to call service input_datetime/set_datetime. must contain al least one of date, time, detetime, timestamp"

Thank you vey much for any help or suggestion.
