### ISSUE TITLE
Cast: Cannot read property 'hass' of null

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#7]
Seems Cast has issues with the card?

```
  - type: entities
    title: Entity templates!
    show_header_toggle: false
    entities:
      - sensor.hue_capabilities
      - type: custom:template-entity-row
        icon: >
          mdi:weather-{{'sunny' if is_state('sun.sun','above_horizon') else 'night'}}
        name: >
          Goede {{'dag' if is_state('sun.sun','above_horizon') else 'nacht'}}
        state: >
          {{states('sun.sun')}}
        condition: "{{is_state('device_tracker.life360_marijn', 'home')}}"
        secondary: >
          Marijn is {{states('device_tracker.life360_marijn')}}
        active: "{{ is_state('device_tracker.life360_marijn', 'home') }}"
```

shows fine on regular Lovelace, but errors red with:
```
Cannot read property 'hass' of null
```

<img width="296" alt="Schermafbeelding 2020-01-10 om 11 11 29" src="https://user-images.githubusercontent.com/33354141/72145063-f912e780-3399-11ea-9ffd-4dcb0c21a629.png">

please have a look? thanks
