### ISSUE TITLE
input_select not rendered as dropdown

### ISSUE THREAD

**Issue by nottledim** [thomasloven/lovelace-template-entity-row#70]
In an entity card if I have the following the choices are presented as a dropdown list:
```       
           - entity: input_select.charge_rate
```
If I use template entity row it just displays current selection but doesn't offer the dropdown list for selection:
```
           - type: 'custom:template-entity-row'
             entity: input_select.charge_rate
```

**Comment by rbnmk** [comment]
@nottledim  did you find a solution/workaround for your issue?

I have the same issue, I am creating a dashboard that will help me start playing music throughout the house. I have the luxury of having Google Chromecast & Sonos speakers (/sigh) so I am trying to determine with a input select which type of speaker(s) I will be targetting for the action. This custom type card seems promising if this could be fixed. 

example:
![2021-12-08_14h59_52](https://user-images.githubusercontent.com/37404233/145221184-ed32e92a-3933-4afe-b1d8-a2849d59a990.gif)

**Comment by nottledim** [comment]
Nice demonstration!  No, in answer to your question.  You can select it from the entity settings popup as you show but that's not ideal.

**Comment by calisro** [comment]
Couldn't you wrap that input_select in a hui-element?

**Comment by calisro** [comment]
`
type: entities
entities:
  - type: 'custom:template-entity-row'  
    entity: input_select.pool_light_select
  - type: custom:hui-element  
    card_type: entities
    entities: 
      - input_select.pool_light_select
`

**Comment by nottledim** [comment]
Interesting, I was unaware of hui-element.  It doesn't really help; I use template-entity-row mostly for it's conditional feature. Without that I would use a normal entities row.  However if I do use hui-element it creates a nested entities card which effectively indents the  rows (icons don't line up).  It doesn't seem to play with template-entity row either. So I don't really see the point of it (hui-element) in this situation.

**Comment by calisro** [comment]
I think you're not configuring it correctly.  Paste an example of your yaml.  I use it quite a bit and all lines up. perfectly.

**Comment by nottledim** [comment]
These are 4 variants I've tried, all rows in an entities card:
```
  - entity: input_select.charge_rate
    name: Charge Rate A

  - type: 'custom:template-entity-row'
    entity: input_select.charge_rate
    name: Charge Rate B
#    condition: '{{ not is_state(''binary_sensor.i3_120_connection_status'', ''off'') }} '

  - type: custom:hui-element
    card_type: custom:template-entity-row
    entity: input_select.charge_rate
    name: Charge Rate C
#    condition: '{{ not is_state(''binary_sensor.i3_120_connection_status'', ''off'') }} '

  - type: custom:hui-element
    card_type: entities
    entities:
      - entity: input_select.charge_rate
        name: Charge Rate D
```
The condition statements are commented so the row renders.  
A:  renders a dropdown, B&C render the same but no dropdown, and D renders a dropdown but is indented.

I'm open to suggestions for more ways to do this :-)

**Comment by calisro** [comment]
You could use card_mod to change the padding for D and line them back up.

```
type: entities
entities:
  - entity: input_select.pool_light_select
    name: Charge Rate A
  - type: custom:template-entity-row
    entity: input_select.pool_light_select
    name: Charge Rate B
  - type: custom:hui-element
    card_type: custom:template-entity-row
    entity: input_select.pool_light_select
    name: Charge Rate C
  - type: custom:hui-element
    card_type: entities
    style: |
      .card-content {
        padding: 0
      }
    entities:
      - entity: input_select.pool_light_select
        name: Charge Rate D
```

**Comment by ildar170975** [comment]
> - type: custom:hui-element
>     card_type: custom:template-entity-row
>     entity: input_select.pool_light_select
>     name: Charge Rate C

This will not work definitely.
I guess the `hui-element` only accepts conventional cards/rows.

**Comment by ildar170975** [comment]
> If I use template entity row it just displays current selection but doesn't offer the dropdown list for selection:

What was the final goal?
Why do you need the input_select inside the `template-entity-row`?

**Comment by ildar170975** [comment]
> have the same issue, I am creating a dashboard that will help me start playing music throughout the house. I have the luxury of having Google Chromecast & Sonos speakers (/sigh) so I am trying to determine with a input select which type of speaker(s) I will be targetting for the action

Correct my understanding if I made a mistake:
1) You have `input_select.type_of_device` (dev-1, dev_2, dev_3).
2) For each of these devices you have settings: `input_select.settings_for_device_1`, `input_select.settings_for_device_2`, `input_select.settings_for_device_3`.
3) Dependingly of the selected device (`input_select.type_of_device`) you need to display the corresponding `input_select.settings_for_device_xxxx` field.

Am I right?
If so - this is not supposed to be solved by the `template-entity-row`.
Use custom `state-switch` card (Thomas Loven).

**Comment by nottledim** [comment]
Thanks for all the suggestions.
@calisro  setting "padding: 0" works but has to be applied to the input_select not the entity:
```
  - type: custom:hui-element
    card_type: entities
    entities:
      - entity: input_select.charge_rate
        name: Charge Rate D
        style: |
          .card-content {
          padding: 0
          }
```
 However your other suggestion is neater and does exactly what I want:
```
  - type: conditional
    conditions:
      - entity: binary_sensor.i3_120_connection_status
        state_not: 'off'
    row:
      entity: input_select.charge_rate
      name: Charge Rate E
```
Many thanks for that. It's been a great help.

@ildar170975 Why do you need the input_select inside the template-entity-row? Because I want to display only when charging and template-entity-row has that feature.  Now I know there's another way - live and learn!
