### ISSUE TITLE
Ability to use `template-entity-row` inside a "clickable" head of `fold-entity-row`

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-template-entity-row#79]
Consider this example:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          icon: mdi:car
          state: ''
          name: some label
        <<: &ref_settings
          open: true
          padding: 0
          #clickable: true
          entities:
            - entity: sun.sun
            - entity: sun.sun
            - entity: sun.sun
  - type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          icon: mdi:car
          state: ''
          name: ''
        <<: *ref_settings
```
![image](https://user-images.githubusercontent.com/71872483/176560995-3a1dc3b3-1ed4-48bb-9afd-b377ef0d51a7.png)

Both cards are SAME, but the 1st card has a `name` specified.

Tapping on the head row on the 1st card - does NOT fold/unfold a list.
Tapping on the head row on the 2nd card - DOES.

Specifying a `clickable` option does not help.

Is it a bug?

**Comment by ildar170975** [comment]
Sorry, my mistake.
Here is a working code - added "fire-dom-event":
```
  - type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          icon: mdi:car
          name: some name + fire-dom
          tap_action:
            action: fire-dom-event
            fold_row: true
        open: true
        padding: 0
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
```
