### ISSUE TITLE
State not getting updated as expected

### ISSUE THREAD

**Issue by kaizersoje** [thomasloven/lovelace-template-entity-row#86]
I have created a row that displays how long a sensor value has changed. However, I have noticed that the value is not getting updated as expected.

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:bed-king
    name: Bedroom
    state: |-
      {{   relative_time(states.sensor.temperature_lumi_158d000418a254.last_changed)  ~ " ago" }}
  - entity: sensor.temperature_lumi_158d000418a254
    secondary_info: last-changed
```

![image](https://user-images.githubusercontent.com/54566217/193811805-43c879be-6797-48d4-9040-a774df0a1323.png)

It shows 33 minutes in the `more-info` dialog for the entity.

The value in the template row gets updated only when I refresh the screen.

**Comment by ildar170975** [comment]
This is about `relative_time`.

Try to reproduce my test:
1. Add this card:
```
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:bed-king
    name: Bedroom
    state: '{{relative_time(states.input_number.test_number.last_changed)}}'
  - entity: input_number.test_number
    secondary_info: last-changed
```
2. Place the browser's window on the left part of your monitor.
3. Open 2nd browser's window, place it on the right side of the monitor.
4. Open Dev Tools -> Template., add this template: `{{relative_time(states.input_number.test_number.last_changed)}}`
5. Change the helper's value and wait for 1 minute.

![Untitled Project](https://user-images.githubusercontent.com/71872483/193943967-ebe1fcb1-232d-4f6c-87c0-1e4a66ad2060.gif)
