### ISSUE TITLE
Is it possible to dynamically show an icon as the `state` value (right side)?

### ISSUE THREAD

**Issue by nickdos** [thomasloven/lovelace-template-entity-row#88]
I'm configuring an entity card where I want the `state` part to show an icon via a template expression. The icon value is coming from an entity attribute.

```yaml
  - type: custom:template-entity-row
    state: >-
      {% if  state_attr('sensor.recycling_collection', 'days') < state_attr('sensor.green_waste_collection', 'days') %}
      {{ state_attr('sensor.recycling_collection', 'icon') }} {% else %} {{ state_attr('sensor.green_waste_collection', 'icon') }} {% endif %}
    name: Next waste collection
    icon: mdi:trash-can
    active: '{{ state_attr(''sensor.garbage_collection'', ''days'') < 2 }}'
```

<img width="474" alt="image" src="https://user-images.githubusercontent.com/532845/197420951-e9637520-aea0-4f74-8fab-aad3394a9dd1.png">

This is just showing the text value for the icon and not the actual icon. Is there a way to display the icon itself?
