### ISSUE TITLE
number slider not visible

### ISSUE THREAD

**Issue by ChristophCaina** [thomasloven/lovelace-template-entity-row#89]
Hi,
I've decided to use the template-entity-row to change the color of the icon from a number-slider.
The Entity I am referring to is a cover / shutter - and I am using the default entities card from HomeAssistant - which does only provide the slider in the "more info" section.

Therefore, I've created a number template, which does call the service to change the position...

Now, when I add the template, the slider disappears.

```
type: entities
entities:
  - entity: cover.schalter_rolladen_wohnzimmer_ost
    secondary_info: position
    name: Rolladen Wohnzimmer (Ost)
  - type: custom:template-entity-row
    entity: number.rolladen_wohnzimmer_ost_set_position
    name: Position setzen
    active: '{{ is_state(''cover.schalter_rolladen_wohnzimmer_ost'', ''open'') }}'
    icon: mdi:window-shutter-settings
state_color: true
```

Card with enabled template:
![grafik](https://user-images.githubusercontent.com/26391061/197504537-34849254-66e3-4689-80a5-ff102463a202.png)
The color changing is working as expected, but the slider disappeared.

Card with disabled template:
![grafik](https://user-images.githubusercontent.com/26391061/197504720-2706ef4d-69da-4621-af14-e510037ed8c6.png)

Card with enabled template and without template for the same number silider:
![grafik](https://user-images.githubusercontent.com/26391061/197505368-a3c49b37-11c4-460b-9c89-d9e758bceaa1.png)
