### ISSUE TITLE
entity state translations are not working

### ISSUE THREAD

**Issue by ChristophCaina** [thomasloven/lovelace-template-entity-row#90]
Another Issue I've just noticed is related to translated states of an entity.

I want to use the template-entity-row for a door-handle sensor.
This sensor can have the following states:

closed / opened / tilted

While using the entity in a normal entities card, the state will be translated into my UI language just as expected.
As soon, as I use the template-entity-row on this entity, the state will be shown in language:

Card with enabled template-entity - the last entity is with applied template:
![grafik](https://user-images.githubusercontent.com/26391061/197508506-fbb6b3c7-a96e-4b53-bc5e-86a7a0818b62.png)

Card with the same entity applied with - and without template:
![grafik](https://user-images.githubusercontent.com/26391061/197508556-e2eb8535-2656-4ea1-863e-11d284df1438.png)

It would be nice, if the entity row would support the built in UI translation.
I know, I could change that by adding an if / else to the 'state'... but that will cause issues, when someone would change the UI language in the user-settings.

**Comment by ildar170975** [comment]
You said "translations are not working" - but you did not use a localization.
![image](https://user-images.githubusercontent.com/71872483/197902658-4998b711-5b0c-4610-a24c-c7d4459aa70b.png)

```
type: entities
entities:
  - cover.garage_door
  - type: custom:template-entity-row
    entity: cover.garage_door
    name: Door
    state: My door is _(component.cover.state._.{{states(config.entity)}})
```
![image](https://user-images.githubusercontent.com/71872483/197902743-779ae9ef-1dd3-4c55-b71e-6fd93afd598e.png)
![image](https://user-images.githubusercontent.com/71872483/197902752-4a309177-551c-49a3-81b7-04aa283b0fe3.png)
