### ISSUE TITLE
custom icon is not dispalyed sometimes

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-template-entity-row#93]
There is a custom "phu" icon from this package:
https://github.com/elax46/custom-brand-icons

The package is installed via HACS & declared here too:
```
frontend:
  extra_module_url:
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
```

The icon is used to customize some entity and is displayed persistently in Lovelace.
But it may NOT be displayed when used in `template-entity-row`.

Consider this code:
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: device_tracker.xiaomi_roborock_s5

  - type: custom:template-entity-row
    entity: sun.sun
    icon: phu:roborock

  - type: custom:template-entity-row
    entity: sun.sun
    icon: '{{state_attr("device_tracker.xiaomi_roborock_s5","icon") }}'

  - type: custom:template-entity-row
    entity: sun.sun
    icon: '{{state_attr("device_tracker.ac68u_ping_device_tracker","icon") }}'
```
The icon is `phu:roborock`, the customized entity is `device_tracker.xiaomi_roborock_s5`.
In the code above the icon is supposed to be displayed:
-- Line 1: as an icon of an entity;
-- Line 2: as an explicitly defined icon (`icon: xxxx`);
-- Line 3: as an icon taken from an attribute (`state_attr(xxx,'icon')`).
-- Line 4: here a different MDI icon is taken from an attribute of another entity (to demonstrate that using `state_attr()` works).

Here is how it should be displayed:
![image](https://user-images.githubusercontent.com/71872483/202699772-76652f01-b8e9-42a6-9eba-b0d324321f89.png)

But this custom "phu" icon is usually displayed in Editor window only - if defined using `state_attr()`:
![image](https://user-images.githubusercontent.com/71872483/202700790-6ffaedd6-ad6c-4533-b483-58c64340bd75.png)

Sometimes the icon displayed on the dashboard too:
![image](https://user-images.githubusercontent.com/71872483/202700949-1c444cd4-98cf-4a1e-b261-a2f8aa1ba666.png)
But after pressing F5 is disappeared again.

Win 10x64, Chrome
2022.11.3
latest `template-entity-row`  (1.3.0)
