### ISSUE TITLE
2022.12: by default an icon's color is same as for a "light" entity

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-template-entity-row#94]
Consider this example:
```
type: entities
entities:
  - type: custom:template-entity-row
    name: name
    icon: mdi:cogs
```
There is no entity specified.
And yet the icon's color is set like for a "light" domain:
![изображение](https://user-images.githubusercontent.com/71872483/206366916-7223022a-64d7-4fcd-8e3d-ed083429e4f5.png)
![изображение](https://user-images.githubusercontent.com/71872483/206367025-469d22e3-b169-4231-b5f7-41ad6f8005d7.png)
