### ISSUE TITLE
history-graph - name template not working

### ISSUE THREAD

**Issue by chadbaldwin** [thomasloven/lovelace-template-entity-row#98]
I've gone through the docs for `auto-entities`, `history-graph` and `template-entity-row`...but I can't seem to figure out where I've gone wrong.

I'm trying to use `template-entity-row` to set a custom `name:` property within a `history-graph` which is populated using `auto-entities`.

I have plenty of other cards that combine `auto-entities` and `template-entity-row` to set custom names and they all work great. But for some reason, specific to `history-graph`, it is not working.

"Not working" in this case means, the templates are being rendered literally. So if I set `name: "{{ 'abc' }}"`, then the resulting name is `{{ 'abc' }}` literally.

Here is an example script:

```yaml
type: custom:auto-entities
card:
  type: history-graph
  refresh_interval: 5
  hours_to_show: 6
filter:
  include:
    - entity_id: /^switch\.outlet_\d\d_switch$/
      options:
        type: custom:template-entity-row
        name: "{{ 'abc' }}"
```

The result is this:

![image](https://user-images.githubusercontent.com/16479446/212381693-efb03ef2-1802-4e2f-8193-31183ebda874.png)

I don't see any issues with my configuration, so my best guess is that this is either a bug, or `history-graph` is just not supported by `template-entity-row`.
